// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: transport/pb/control.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Control struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*Control_Hello
	//	*Control_GoAway
	Message       isControl_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Control) Reset() {
	*x = Control{}
	mi := &file_transport_pb_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Control) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Control) ProtoMessage() {}

func (x *Control) ProtoReflect() protoreflect.Message {
	mi := &file_transport_pb_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Control.ProtoReflect.Descriptor instead.
func (*Control) Descriptor() ([]byte, []int) {
	return file_transport_pb_control_proto_rawDescGZIP(), []int{0}
}

func (x *Control) GetMessage() isControl_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Control) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Message.(*Control_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Control) GetGoAway() *GoAway {
	if x != nil {
		if x, ok := x.Message.(*Control_GoAway); ok {
			return x.GoAway
		}
	}
	return nil
}

type isControl_Message interface {
	isControl_Message()
}

type Control_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type Control_GoAway struct {
	GoAway *GoAway `protobuf:"bytes,2,opt,name=go_away,json=goAway,proto3,oneof"`
}

func (*Control_Hello) isControl_Message() {}

func (*Control_GoAway) isControl_Message() {}

type Hello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Selectors this endpoint serves, strictly ascending, at most 1024, none zero.
	Selectors []uint64 `protobuf:"varint,1,rep,packed,name=selectors,proto3" json:"selectors,omitempty"`
	// Optional: the sender's current node record (EIP-778 RLP encoding).
	Record        []byte `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_transport_pb_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_transport_pb_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_transport_pb_control_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetSelectors() []uint64 {
	if x != nil {
		return x.Selectors
	}
	return nil
}

func (x *Hello) GetRecord() []byte {
	if x != nil {
		return x.Record
	}
	return nil
}

type GoAway struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A stack-namespace code value (spec 008 section 5.2).
	Code          uint64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoAway) Reset() {
	*x = GoAway{}
	mi := &file_transport_pb_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoAway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoAway) ProtoMessage() {}

func (x *GoAway) ProtoReflect() protoreflect.Message {
	mi := &file_transport_pb_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoAway.ProtoReflect.Descriptor instead.
func (*GoAway) Descriptor() ([]byte, []int) {
	return file_transport_pb_control_proto_rawDescGZIP(), []int{2}
}

func (x *GoAway) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_transport_pb_control_proto protoreflect.FileDescriptor

const file_transport_pb_control_proto_rawDesc = "" +
	"\n" +
	"\x1atransport/pb/control.proto\x12\x10ethp2p.transport\"z\n" +
	"\aControl\x12/\n" +
	"\x05hello\x18\x01 \x01(\v2\x17.ethp2p.transport.HelloH\x00R\x05hello\x123\n" +
	"\ago_away\x18\x02 \x01(\v2\x18.ethp2p.transport.GoAwayH\x00R\x06goAwayB\t\n" +
	"\amessage\"=\n" +
	"\x05Hello\x12\x1c\n" +
	"\tselectors\x18\x01 \x03(\x04R\tselectors\x12\x16\n" +
	"\x06record\x18\x02 \x01(\fR\x06record\"\x1c\n" +
	"\x06GoAway\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x04R\x04codeB'Z%github.com/ethp2p/ethp2p/transport/pbb\x06proto3"

var (
	file_transport_pb_control_proto_rawDescOnce sync.Once
	file_transport_pb_control_proto_rawDescData []byte
)

func file_transport_pb_control_proto_rawDescGZIP() []byte {
	file_transport_pb_control_proto_rawDescOnce.Do(func() {
		file_transport_pb_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_pb_control_proto_rawDesc), len(file_transport_pb_control_proto_rawDesc)))
	})
	return file_transport_pb_control_proto_rawDescData
}

var file_transport_pb_control_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_transport_pb_control_proto_goTypes = []any{
	(*Control)(nil), // 0: ethp2p.transport.Control
	(*Hello)(nil),   // 1: ethp2p.transport.Hello
	(*GoAway)(nil),  // 2: ethp2p.transport.GoAway
}
var file_transport_pb_control_proto_depIdxs = []int32{
	1, // 0: ethp2p.transport.Control.hello:type_name -> ethp2p.transport.Hello
	2, // 1: ethp2p.transport.Control.go_away:type_name -> ethp2p.transport.GoAway
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_transport_pb_control_proto_init() }
func file_transport_pb_control_proto_init() {
	if File_transport_pb_control_proto != nil {
		return
	}
	file_transport_pb_control_proto_msgTypes[0].OneofWrappers = []any{
		(*Control_Hello)(nil),
		(*Control_GoAway)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_pb_control_proto_rawDesc), len(file_transport_pb_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transport_pb_control_proto_goTypes,
		DependencyIndexes: file_transport_pb_control_proto_depIdxs,
		MessageInfos:      file_transport_pb_control_proto_msgTypes,
	}.Build()
	File_transport_pb_control_proto = out.File
	file_transport_pb_control_proto_goTypes = nil
	file_transport_pb_control_proto_depIdxs = nil
}
