// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: broadcast/rs/pb/rs.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Preamble is the session preamble for Reed-Solomon coded messages.
type Preamble struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumData       int32                  `protobuf:"varint,1,opt,name=num_data,json=numData,proto3" json:"num_data,omitempty"`
	NumParity     int32                  `protobuf:"varint,2,opt,name=num_parity,json=numParity,proto3" json:"num_parity,omitempty"`
	Length        int32                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	Hashes        [][]byte               `protobuf:"bytes,4,rep,name=hashes,proto3" json:"hashes,omitempty"`
	Hash          []byte                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Preamble) Reset() {
	*x = Preamble{}
	mi := &file_broadcast_rs_pb_rs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Preamble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Preamble) ProtoMessage() {}

func (x *Preamble) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_rs_pb_rs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Preamble.ProtoReflect.Descriptor instead.
func (*Preamble) Descriptor() ([]byte, []int) {
	return file_broadcast_rs_pb_rs_proto_rawDescGZIP(), []int{0}
}

func (x *Preamble) GetNumData() int32 {
	if x != nil {
		return x.NumData
	}
	return 0
}

func (x *Preamble) GetNumParity() int32 {
	if x != nil {
		return x.NumParity
	}
	return 0
}

func (x *Preamble) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Preamble) GetHashes() [][]byte {
	if x != nil {
		return x.Hashes
	}
	return nil
}

func (x *Preamble) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// ChunkIdent identifies an RS chunk (shard) on the wire.
type ChunkIdent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkIdent) Reset() {
	*x = ChunkIdent{}
	mi := &file_broadcast_rs_pb_rs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkIdent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkIdent) ProtoMessage() {}

func (x *ChunkIdent) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_rs_pb_rs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkIdent.ProtoReflect.Descriptor instead.
func (*ChunkIdent) Descriptor() ([]byte, []int) {
	return file_broadcast_rs_pb_rs_proto_rawDescGZIP(), []int{1}
}

func (x *ChunkIdent) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

var File_broadcast_rs_pb_rs_proto protoreflect.FileDescriptor

const file_broadcast_rs_pb_rs_proto_rawDesc = "" +
	"\n" +
	"\x18broadcast/rs/pb/rs.proto\x12\x13ethp2p.broadcast.rs\"\x88\x01\n" +
	"\bPreamble\x12\x19\n" +
	"\bnum_data\x18\x01 \x01(\x05R\anumData\x12\x1d\n" +
	"\n" +
	"num_parity\x18\x02 \x01(\x05R\tnumParity\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x05R\x06length\x12\x16\n" +
	"\x06hashes\x18\x04 \x03(\fR\x06hashes\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\fR\x04hash\"\"\n" +
	"\n" +
	"ChunkIdent\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05indexB*Z(github.com/ethp2p/ethp2p/broadcast/rs/pbb\x06proto3"

var (
	file_broadcast_rs_pb_rs_proto_rawDescOnce sync.Once
	file_broadcast_rs_pb_rs_proto_rawDescData []byte
)

func file_broadcast_rs_pb_rs_proto_rawDescGZIP() []byte {
	file_broadcast_rs_pb_rs_proto_rawDescOnce.Do(func() {
		file_broadcast_rs_pb_rs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_broadcast_rs_pb_rs_proto_rawDesc), len(file_broadcast_rs_pb_rs_proto_rawDesc)))
	})
	return file_broadcast_rs_pb_rs_proto_rawDescData
}

var file_broadcast_rs_pb_rs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_broadcast_rs_pb_rs_proto_goTypes = []any{
	(*Preamble)(nil),   // 0: ethp2p.broadcast.rs.Preamble
	(*ChunkIdent)(nil), // 1: ethp2p.broadcast.rs.ChunkIdent
}
var file_broadcast_rs_pb_rs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_broadcast_rs_pb_rs_proto_init() }
func file_broadcast_rs_pb_rs_proto_init() {
	if File_broadcast_rs_pb_rs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_broadcast_rs_pb_rs_proto_rawDesc), len(file_broadcast_rs_pb_rs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_broadcast_rs_pb_rs_proto_goTypes,
		DependencyIndexes: file_broadcast_rs_pb_rs_proto_depIdxs,
		MessageInfos:      file_broadcast_rs_pb_rs_proto_msgTypes,
	}.Build()
	File_broadcast_rs_pb_rs_proto = out.File
	file_broadcast_rs_pb_rs_proto_goTypes = nil
	file_broadcast_rs_pb_rs_proto_depIdxs = nil
}
