// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: broadcast/pb/broadcast.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bcast is the control frame exchanged on the per-peer BCAST stream.
// Carries handshake, subscribe, and unsubscribe messages.
type Bcast struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*Bcast_PeerHandshake
	//	*Bcast_ChannelSubscribe
	//	*Bcast_ChannelUnsubscribe
	Message       isBcast_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bcast) Reset() {
	*x = Bcast{}
	mi := &file_broadcast_pb_broadcast_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bcast) ProtoMessage() {}

func (x *Bcast) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_pb_broadcast_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bcast.ProtoReflect.Descriptor instead.
func (*Bcast) Descriptor() ([]byte, []int) {
	return file_broadcast_pb_broadcast_proto_rawDescGZIP(), []int{0}
}

func (x *Bcast) GetMessage() isBcast_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Bcast) GetPeerHandshake() *Bcast_Handshake {
	if x != nil {
		if x, ok := x.Message.(*Bcast_PeerHandshake); ok {
			return x.PeerHandshake
		}
	}
	return nil
}

func (x *Bcast) GetChannelSubscribe() *Bcast_Subscribe {
	if x != nil {
		if x, ok := x.Message.(*Bcast_ChannelSubscribe); ok {
			return x.ChannelSubscribe
		}
	}
	return nil
}

func (x *Bcast) GetChannelUnsubscribe() *Bcast_Unsubscribe {
	if x != nil {
		if x, ok := x.Message.(*Bcast_ChannelUnsubscribe); ok {
			return x.ChannelUnsubscribe
		}
	}
	return nil
}

type isBcast_Message interface {
	isBcast_Message()
}

type Bcast_PeerHandshake struct {
	PeerHandshake *Bcast_Handshake `protobuf:"bytes,1,opt,name=peer_handshake,json=peerHandshake,proto3,oneof"`
}

type Bcast_ChannelSubscribe struct {
	ChannelSubscribe *Bcast_Subscribe `protobuf:"bytes,2,opt,name=channel_subscribe,json=channelSubscribe,proto3,oneof"`
}

type Bcast_ChannelUnsubscribe struct {
	ChannelUnsubscribe *Bcast_Unsubscribe `protobuf:"bytes,3,opt,name=channel_unsubscribe,json=channelUnsubscribe,proto3,oneof"`
}

func (*Bcast_PeerHandshake) isBcast_Message() {}

func (*Bcast_ChannelSubscribe) isBcast_Message() {}

func (*Bcast_ChannelUnsubscribe) isBcast_Message() {}

// Sess is the frame type carried on per-session SESS streams.
// The first frame MUST be Open (which may carry initial routing
// state inline); subsequent frames are Update.
type Sess struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*Sess_SessionOpen
	//	*Sess_RoutingUpdate
	Frame         isSess_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sess) Reset() {
	*x = Sess{}
	mi := &file_broadcast_pb_broadcast_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sess) ProtoMessage() {}

func (x *Sess) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_pb_broadcast_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sess.ProtoReflect.Descriptor instead.
func (*Sess) Descriptor() ([]byte, []int) {
	return file_broadcast_pb_broadcast_proto_rawDescGZIP(), []int{1}
}

func (x *Sess) GetFrame() isSess_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *Sess) GetSessionOpen() *Sess_Open {
	if x != nil {
		if x, ok := x.Frame.(*Sess_SessionOpen); ok {
			return x.SessionOpen
		}
	}
	return nil
}

func (x *Sess) GetRoutingUpdate() *Sess_Update {
	if x != nil {
		if x, ok := x.Frame.(*Sess_RoutingUpdate); ok {
			return x.RoutingUpdate
		}
	}
	return nil
}

type isSess_Frame interface {
	isSess_Frame()
}

type Sess_SessionOpen struct {
	SessionOpen *Sess_Open `protobuf:"bytes,1,opt,name=session_open,json=sessionOpen,proto3,oneof"`
}

type Sess_RoutingUpdate struct {
	RoutingUpdate *Sess_Update `protobuf:"bytes,2,opt,name=routing_update,json=routingUpdate,proto3,oneof"`
}

func (*Sess_SessionOpen) isSess_Frame() {}

func (*Sess_RoutingUpdate) isSess_Frame() {}

// Chunk is the protocol namespace for chunk streams.
type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_broadcast_pb_broadcast_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_pb_broadcast_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_broadcast_pb_broadcast_proto_rawDescGZIP(), []int{2}
}

// Handshake is the first message exchanged on a BCAST stream.
type Bcast_Handshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Channels      []string               `protobuf:"bytes,2,rep,name=channels,proto3" json:"channels,omitempty"`
	PeerId        string                 `protobuf:"bytes,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bcast_Handshake) Reset() {
	*x = Bcast_Handshake{}
	mi := &file_broadcast_pb_broadcast_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bcast_Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bcast_Handshake) ProtoMessage() {}

func (x *Bcast_Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_pb_broadcast_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bcast_Handshake.ProtoReflect.Descriptor instead.
func (*Bcast_Handshake) Descriptor() ([]byte, []int) {
	return file_broadcast_pb_broadcast_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Bcast_Handshake) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Bcast_Handshake) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *Bcast_Handshake) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

// Subscribe requests the remote peer to include us in a channel.
type Bcast_Subscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bcast_Subscribe) Reset() {
	*x = Bcast_Subscribe{}
	mi := &file_broadcast_pb_broadcast_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bcast_Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bcast_Subscribe) ProtoMessage() {}

func (x *Bcast_Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_pb_broadcast_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bcast_Subscribe.ProtoReflect.Descriptor instead.
func (*Bcast_Subscribe) Descriptor() ([]byte, []int) {
	return file_broadcast_pb_broadcast_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Bcast_Subscribe) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

// Unsubscribe requests removal from a channel.
type Bcast_Unsubscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bcast_Unsubscribe) Reset() {
	*x = Bcast_Unsubscribe{}
	mi := &file_broadcast_pb_broadcast_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bcast_Unsubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bcast_Unsubscribe) ProtoMessage() {}

func (x *Bcast_Unsubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_pb_broadcast_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bcast_Unsubscribe.ProtoReflect.Descriptor instead.
func (*Bcast_Unsubscribe) Descriptor() ([]byte, []int) {
	return file_broadcast_pb_broadcast_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Bcast_Unsubscribe) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

// Open is the first frame on a SESS stream, establishing the session.
type Sess_Open struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Preamble      []byte                 `protobuf:"bytes,3,opt,name=preamble,proto3" json:"preamble,omitempty"`
	InitialUpdate []byte                 `protobuf:"bytes,4,opt,name=initial_update,json=initialUpdate,proto3" json:"initial_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sess_Open) Reset() {
	*x = Sess_Open{}
	mi := &file_broadcast_pb_broadcast_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sess_Open) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sess_Open) ProtoMessage() {}

func (x *Sess_Open) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_pb_broadcast_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sess_Open.ProtoReflect.Descriptor instead.
func (*Sess_Open) Descriptor() ([]byte, []int) {
	return file_broadcast_pb_broadcast_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Sess_Open) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Sess_Open) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Sess_Open) GetPreamble() []byte {
	if x != nil {
		return x.Preamble
	}
	return nil
}

func (x *Sess_Open) GetInitialUpdate() []byte {
	if x != nil {
		return x.InitialUpdate
	}
	return nil
}

// Update carries an opaque routing state update (e.g. bitmap, have list).
type Sess_Update struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sess_Update) Reset() {
	*x = Sess_Update{}
	mi := &file_broadcast_pb_broadcast_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sess_Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sess_Update) ProtoMessage() {}

func (x *Sess_Update) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_pb_broadcast_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sess_Update.ProtoReflect.Descriptor instead.
func (*Sess_Update) Descriptor() ([]byte, []int) {
	return file_broadcast_pb_broadcast_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Sess_Update) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Header prefixes each chunk on a CHUNK stream. The receiver reads
// data_length raw bytes from the stream immediately after the header.
type Chunk_Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ChunkId       []byte                 `protobuf:"bytes,3,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	DataLength    uint32                 `protobuf:"varint,4,opt,name=data_length,json=dataLength,proto3" json:"data_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk_Header) Reset() {
	*x = Chunk_Header{}
	mi := &file_broadcast_pb_broadcast_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk_Header) ProtoMessage() {}

func (x *Chunk_Header) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_pb_broadcast_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk_Header.ProtoReflect.Descriptor instead.
func (*Chunk_Header) Descriptor() ([]byte, []int) {
	return file_broadcast_pb_broadcast_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Chunk_Header) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Chunk_Header) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Chunk_Header) GetChunkId() []byte {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *Chunk_Header) GetDataLength() uint32 {
	if x != nil {
		return x.DataLength
	}
	return 0
}

var File_broadcast_pb_broadcast_proto protoreflect.FileDescriptor

const file_broadcast_pb_broadcast_proto_rawDesc = "" +
	"\n" +
	"\x1cbroadcast/pb/broadcast.proto\x12\x10ethp2p.broadcast\"\xb4\x03\n" +
	"\x05Bcast\x12J\n" +
	"\x0epeer_handshake\x18\x01 \x01(\v2!.ethp2p.broadcast.Bcast.HandshakeH\x00R\rpeerHandshake\x12P\n" +
	"\x11channel_subscribe\x18\x02 \x01(\v2!.ethp2p.broadcast.Bcast.SubscribeH\x00R\x10channelSubscribe\x12V\n" +
	"\x13channel_unsubscribe\x18\x03 \x01(\v2#.ethp2p.broadcast.Bcast.UnsubscribeH\x00R\x12channelUnsubscribe\x1aZ\n" +
	"\tHandshake\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1a\n" +
	"\bchannels\x18\x02 \x03(\tR\bchannels\x12\x17\n" +
	"\apeer_id\x18\x03 \x01(\tR\x06peerId\x1a%\n" +
	"\tSubscribe\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x1a'\n" +
	"\vUnsubscribe\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannelB\t\n" +
	"\amessage\"\xbc\x02\n" +
	"\x04Sess\x12@\n" +
	"\fsession_open\x18\x01 \x01(\v2\x1b.ethp2p.broadcast.Sess.OpenH\x00R\vsessionOpen\x12F\n" +
	"\x0erouting_update\x18\x02 \x01(\v2\x1d.ethp2p.broadcast.Sess.UpdateH\x00R\rroutingUpdate\x1a\x82\x01\n" +
	"\x04Open\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1a\n" +
	"\bpreamble\x18\x03 \x01(\fR\bpreamble\x12%\n" +
	"\x0einitial_update\x18\x04 \x01(\fR\rinitialUpdate\x1a\x1c\n" +
	"\x06Update\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04dataB\a\n" +
	"\x05frame\"\x86\x01\n" +
	"\x05Chunk\x1a}\n" +
	"\x06Header\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x19\n" +
	"\bchunk_id\x18\x03 \x01(\fR\achunkId\x12\x1f\n" +
	"\vdata_length\x18\x04 \x01(\rR\n" +
	"dataLengthB'Z%github.com/ethp2p/ethp2p/broadcast/pbb\x06proto3"

var (
	file_broadcast_pb_broadcast_proto_rawDescOnce sync.Once
	file_broadcast_pb_broadcast_proto_rawDescData []byte
)

func file_broadcast_pb_broadcast_proto_rawDescGZIP() []byte {
	file_broadcast_pb_broadcast_proto_rawDescOnce.Do(func() {
		file_broadcast_pb_broadcast_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_broadcast_pb_broadcast_proto_rawDesc), len(file_broadcast_pb_broadcast_proto_rawDesc)))
	})
	return file_broadcast_pb_broadcast_proto_rawDescData
}

var file_broadcast_pb_broadcast_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_broadcast_pb_broadcast_proto_goTypes = []any{
	(*Bcast)(nil),             // 0: ethp2p.broadcast.Bcast
	(*Sess)(nil),              // 1: ethp2p.broadcast.Sess
	(*Chunk)(nil),             // 2: ethp2p.broadcast.Chunk
	(*Bcast_Handshake)(nil),   // 3: ethp2p.broadcast.Bcast.Handshake
	(*Bcast_Subscribe)(nil),   // 4: ethp2p.broadcast.Bcast.Subscribe
	(*Bcast_Unsubscribe)(nil), // 5: ethp2p.broadcast.Bcast.Unsubscribe
	(*Sess_Open)(nil),         // 6: ethp2p.broadcast.Sess.Open
	(*Sess_Update)(nil),       // 7: ethp2p.broadcast.Sess.Update
	(*Chunk_Header)(nil),      // 8: ethp2p.broadcast.Chunk.Header
}
var file_broadcast_pb_broadcast_proto_depIdxs = []int32{
	3, // 0: ethp2p.broadcast.Bcast.peer_handshake:type_name -> ethp2p.broadcast.Bcast.Handshake
	4, // 1: ethp2p.broadcast.Bcast.channel_subscribe:type_name -> ethp2p.broadcast.Bcast.Subscribe
	5, // 2: ethp2p.broadcast.Bcast.channel_unsubscribe:type_name -> ethp2p.broadcast.Bcast.Unsubscribe
	6, // 3: ethp2p.broadcast.Sess.session_open:type_name -> ethp2p.broadcast.Sess.Open
	7, // 4: ethp2p.broadcast.Sess.routing_update:type_name -> ethp2p.broadcast.Sess.Update
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_broadcast_pb_broadcast_proto_init() }
func file_broadcast_pb_broadcast_proto_init() {
	if File_broadcast_pb_broadcast_proto != nil {
		return
	}
	file_broadcast_pb_broadcast_proto_msgTypes[0].OneofWrappers = []any{
		(*Bcast_PeerHandshake)(nil),
		(*Bcast_ChannelSubscribe)(nil),
		(*Bcast_ChannelUnsubscribe)(nil),
	}
	file_broadcast_pb_broadcast_proto_msgTypes[1].OneofWrappers = []any{
		(*Sess_SessionOpen)(nil),
		(*Sess_RoutingUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_broadcast_pb_broadcast_proto_rawDesc), len(file_broadcast_pb_broadcast_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_broadcast_pb_broadcast_proto_goTypes,
		DependencyIndexes: file_broadcast_pb_broadcast_proto_depIdxs,
		MessageInfos:      file_broadcast_pb_broadcast_proto_msgTypes,
	}.Build()
	File_broadcast_pb_broadcast_proto = out.File
	file_broadcast_pb_broadcast_proto_goTypes = nil
	file_broadcast_pb_broadcast_proto_depIdxs = nil
}
